jobs:
- job: Job1
  displayName: Job-1 macOS
  pool:
    vmImage: "macos-latest"
  steps:
    - script: mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../install ..
      displayName: build with cmake
    - script: cd build && ls
      displayName: check build dir
    - script: cd build && make && make install
      displayName: install
    - script: cd install && ls && cd python-bindings && ls
      displayName: check installed proj tree
    - script: cd install && cp test-bindings.py lib*
      displayName: copies the test script into lib folder
    - script: cd install && cd test-bindings && cd lib* && python3 test-bindings.py
      displayName: runs the bindings
    