jobs:
- job: Job1
  displayName: Job-1 macOS
  pool:
    vmImage: "macos-latest"
  steps:
    - script: cmake --version
      displayName: check if cmake is present
    - script: which g++ && which gcc && gcc -v
      displayName: check c++ compilers
    