jobs:
# - job: Job1
#   displayName: Job-1 macOS Catalina
#   pool:
#     vmImage: "macos-latest"
#   steps:
#     - script: mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../install ..
#       displayName: build with cmake
#     - script: cd build && ls
#       displayName: check build dir
#     - script: cd build && make && make install
#       displayName: install
#     - script: cd install && cd python-bindings&& cp randoms.py lib*
#       displayName: copies the test script into lib folder
#     - script: cd install && cd python-bindings && cd lib* && python3 randoms.py
#       displayName: runs the bindings-test

# - job: Job2
#   displayName: Job-2 macOS Mojave
#   pool:
#     vmImage: "macos-10.14"
#   steps:
#     - script: mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../install ..
#       displayName: build with cmake
#     - script: cd build && ls
#       displayName: check build dir
#     - script: cd build && make && make install
#       displayName: install
#     - script: cd install && cd python-bindings&& cp randoms.py lib*
#       displayName: copies the test script into lib folder
#     - script: cd install && cd python-bindings && cd lib* && python3 randoms.py
#       displayName: runs the bindings-test
    
- job: Job3
  displayName: Job-3 Ubuntu
  pool:
    vmImage: "ubuntu-latest"
  steps:
    - script: mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../install ..
      displayName: build with cmake
    - script: cd build &&  make install
      displayName: install
    - script: cd install && cd python-bindings && cd lib* && python3 randoms.py
      displayName: runs the random script
    - script: cd install && cd python-bindings && cd lib* && python3 histogram.py
      displayName: runs the histogram script
    - script: tar -zcvf install-bundle.tar.gz install && cp install-bundle.tar.gz /tmp
      displayName: creates tarball with install dir and copies to tmp
    - script: cd install && cd python-bindings && cd lib* && tar -zcvf plot-bundle.tar.gz output && cp plot-bundle.tar.gz /tmp
      displayName: creates tarball with histograms and copies to tmp
    - publish: /tmp/install-bundle.tar.gz
      artifact: install-bundle
    - publish: /tmp/plot-bundle.tar.gz
      artifact: plot-bundle