jobs:
- job: Job1
  displayName: Job-1 macOS Catalina
  pool:
    vmImage: "macos-latest"
  steps:
    - script: mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../install ..
      displayName: build with cmake
    - script: cd build && ls
      displayName: check build dir
    - script: cd build && make && make install
      displayName: install
    - script: cd install && cd python-bindings&& cp randoms.py lib*
      displayName: copies the test script into lib folder
    - script: cd install && cd python-bindings && cd lib* && python3 randoms.py
      displayName: runs the bindings-test

- job: Job2
  displayName: Job-2 macOS Mojave
  pool:
    vmImage: "macos-10.14"
  steps:
    - script: mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../install ..
      displayName: build with cmake
    - script: cd build && ls
      displayName: check build dir
    - script: cd build && make && make install
      displayName: install
    - script: cd install && cd python-bindings&& cp randoms.py lib*
      displayName: copies the test script into lib folder
    - script: cd install && cd python-bindings && cd lib* && python3 randoms.py
      displayName: runs the bindings-test
    
- job: Job3
  displayName: Job-3 Ubuntu
  pool:
    vmImage: "ubuntu-latest"
  steps:
    - script: mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../install ..
      displayName: build with cmake
    # - script: cd src && python3 setup.py build && cd build && ls && cd lib* && ls
    #   displayName: check build dir
    # - script: cd src && cd build && cd lib* && cp ../../../python/test-bindings.py . && python3 test-bindings.py 
    #   displayName: copies and runs the bindings
    - script: cd build && make && make install
      displayName: install
    - script: cd install && cd python-bindings&& cp randoms.py lib*
      displayName: copies the test script into lib folder
    - script: cd install && cd python-bindings && cd lib* && python3 randoms.py
      displayName: runs the bindings-test
    